// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOsv9fl_gGekigKUCPwJTiOh9uwVSwIys',
    appId: '1:478598579251:web:167449ce18e109334f4f46',
    messagingSenderId: '478598579251',
    projectId: 'pocketmedi000',
    authDomain: 'pocketmedi000.firebaseapp.com',
    storageBucket: 'pocketmedi000.appspot.com',
    measurementId: 'G-DMNE45HKF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgZ6zBMCe05H4J_jx-ileik08UwKHUtSo',
    appId: '1:478598579251:android:1983249d2b3bf2294f4f46',
    messagingSenderId: '478598579251',
    projectId: 'pocketmedi000',
    storageBucket: 'pocketmedi000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsFcUQEQo4IIV2G22O5dpj5U1uoRJqQYc',
    appId: '1:478598579251:ios:9510c558af6912464f4f46',
    messagingSenderId: '478598579251',
    projectId: 'pocketmedi000',
    storageBucket: 'pocketmedi000.appspot.com',
    iosClientId: '478598579251-epqfojm532h33n55km948affpf7tiv9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketmedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsFcUQEQo4IIV2G22O5dpj5U1uoRJqQYc',
    appId: '1:478598579251:ios:9510c558af6912464f4f46',
    messagingSenderId: '478598579251',
    projectId: 'pocketmedi000',
    storageBucket: 'pocketmedi000.appspot.com',
    iosClientId: '478598579251-epqfojm532h33n55km948affpf7tiv9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketmedi',
  );
}
