// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADj77xndf9b_IZse2l00ispU92LBzgGgI',
    appId: '1:1026382703672:web:ac975897b0de2ec75f8acd',
    messagingSenderId: '1026382703672',
    projectId: 'pocketmedi',
    authDomain: 'pocketmedi.firebaseapp.com',
    storageBucket: 'pocketmedi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFggSf9eoKKLDS9fhMCm_LAP4MiDkJq3g',
    appId: '1:1026382703672:android:efb3e87e2a0b429a5f8acd',
    messagingSenderId: '1026382703672',
    projectId: 'pocketmedi',
    storageBucket: 'pocketmedi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBapHMCaqfX6ZO68ZToskq_pW2BMV3PALA',
    appId: '1:1026382703672:ios:308073bf2735fc5c5f8acd',
    messagingSenderId: '1026382703672',
    projectId: 'pocketmedi',
    storageBucket: 'pocketmedi.appspot.com',
    iosClientId: '1026382703672-ujkm2uqpnbnqqej816sie6a23eml7i0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketmedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBapHMCaqfX6ZO68ZToskq_pW2BMV3PALA',
    appId: '1:1026382703672:ios:308073bf2735fc5c5f8acd',
    messagingSenderId: '1026382703672',
    projectId: 'pocketmedi',
    storageBucket: 'pocketmedi.appspot.com',
    iosClientId: '1026382703672-ujkm2uqpnbnqqej816sie6a23eml7i0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketmedi',
  );
}
