// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFnpfMr-ztdiFec4bcC-533jWYQh3Tdfw',
    appId: '1:967439380480:web:2ced747e5b5da149fa28e5',
    messagingSenderId: '967439380480',
    projectId: 'pocketmedi0',
    authDomain: 'pocketmedi0.firebaseapp.com',
    storageBucket: 'pocketmedi0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8s4NKE6_9wb4H9jV4xyz4J5xK9NT5iI',
    appId: '1:967439380480:android:bce741ff2b0ef6c2fa28e5',
    messagingSenderId: '967439380480',
    projectId: 'pocketmedi0',
    storageBucket: 'pocketmedi0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWt9tDFDB4JGPpEiheUkRfRYKhTH9zzQY',
    appId: '1:967439380480:ios:5ab527598c1b0907fa28e5',
    messagingSenderId: '967439380480',
    projectId: 'pocketmedi0',
    storageBucket: 'pocketmedi0.appspot.com',
    iosClientId: '967439380480-ig42b05esd8v76ssotvti6m49sin01k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketmedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWt9tDFDB4JGPpEiheUkRfRYKhTH9zzQY',
    appId: '1:967439380480:ios:5ab527598c1b0907fa28e5',
    messagingSenderId: '967439380480',
    projectId: 'pocketmedi0',
    storageBucket: 'pocketmedi0.appspot.com',
    iosClientId: '967439380480-ig42b05esd8v76ssotvti6m49sin01k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketmedi',
  );
}
